--------------------------------------------------------
--  File created - Wednesday-April-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTI_ANGGOTA
--------------------------------------------------------

  CREATE TABLE "SIA"."PTI_ANGGOTA" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAMA" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(26 BYTE), 
	"NO_TLP" VARCHAR2(13 BYTE), 
	"ALAMAT" VARCHAR2(120 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SIA.PTI_ANGGOTA
SET DEFINE OFF;
Insert into SIA.PTI_ANGGOTA (ID,NAMA,EMAIL,NO_TLP,ALAMAT,PASSWORD) values ('145314000','Elisabeth Kusuma Adi','email','no_tlp','alamat','password');
Insert into SIA.PTI_ANGGOTA (ID,NAMA,EMAIL,NO_TLP,ALAMAT,PASSWORD) values ('145314042','MICHAEL DONNY KUSUMA','mdonnyk@gmail.com','08111111111','Jl. Lempongsari Raya, Sariharjo, Ngaglik, Sleman, D.I. Yogyakarta','mdonnyk');
Insert into SIA.PTI_ANGGOTA (ID,NAMA,EMAIL,NO_TLP,ALAMAT,PASSWORD) values ('145314063','I PUTU BUDHI DARMA P','bluestack.das@gmail.com','081239229537','Jl. Nakula, Blotan, Wedomartani, Sleman, D.I. Yogyakarta','budhi');
--------------------------------------------------------
--  DDL for Index PTI_ANGGOTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_ANGGOTA_PK" ON "SIA"."PTI_ANGGOTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PTI_ANGGOTA_UNIQUE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_ANGGOTA_UNIQUE_EMAIL" ON "SIA"."PTI_ANGGOTA" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PTI_ANGGOTA_UNIQUE_NO_TLP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_ANGGOTA_UNIQUE_NO_TLP" ON "SIA"."PTI_ANGGOTA" ("NO_TLP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTI_ANGGOTA
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("ALAMAT" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("NO_TLP" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_ANGGOTA" ADD CONSTRAINT "PTI_ANGGOTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("ID" NOT NULL ENABLE);
