--------------------------------------------------------
--  File created - Thursday-March-16-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTI_ANGGOTA
--------------------------------------------------------

  CREATE TABLE "SIA"."PTI_ANGGOTA" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NAMA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SIA.PTI_ANGGOTA
SET DEFINE OFF;
Insert into SIA.PTI_ANGGOTA (ID,NAMA) values ('145314042','MICHAEL DONNY KUSUMA');
Insert into SIA.PTI_ANGGOTA (ID,NAMA) values ('145314063','I PUTU BUDHI DARMA P');
--------------------------------------------------------
--  DDL for Index PTI_ANGGOTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_ANGGOTA_PK" ON "SIA"."PTI_ANGGOTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTI_ANGGOTA
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_ANGGOTA" ADD CONSTRAINT "PTI_ANGGOTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_ANGGOTA" MODIFY ("ID" NOT NULL ENABLE);
