--------------------------------------------------------
--  File created - Monday-March-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTI_BUKU
--------------------------------------------------------

  CREATE TABLE "SIA"."PTI_BUKU" 
   (	"ID" NUMBER, 
	"ISBN" VARCHAR2(20 BYTE), 
	"JUDUL" VARCHAR2(250 BYTE), 
	"PENGARANG" VARCHAR2(250 BYTE), 
	"TH_TERBIT" VARCHAR2(4 BYTE), 
	"PENERBIT" VARCHAR2(250 BYTE), 
	"KETERSEDIAAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SIA.PTI_BUKU
SET DEFINE OFF;
Insert into SIA.PTI_BUKU (ID,ISBN,JUDUL,PENGARANG,TH_TERBIT,PENERBIT,KETERSEDIAAN) values (9780596529260001,'978-0-596-52926-0','RESTful Web Services ','Leonard Richardson, Sam Ruby','2007','O''Reilly Media',1);
Insert into SIA.PTI_BUKU (ID,ISBN,JUDUL,PENGARANG,TH_TERBIT,PENERBIT,KETERSEDIAAN) values (9780596000950003,'978-0-596-00095-0','Programming Web Services with SOAP','James Snell, Doug Tidwell, Pavel Kulchenko','2001','O''Reilly Media',3);
Insert into SIA.PTI_BUKU (ID,ISBN,JUDUL,PENGARANG,TH_TERBIT,PENERBIT,KETERSEDIAAN) values (9781449356569002,'978-1-4493-5656-9','PHP Web Services','Lorna Jane Mitchell','2013','O''Reilly Media',2);
Insert into SIA.PTI_BUKU (ID,ISBN,JUDUL,PENGARANG,TH_TERBIT,PENERBIT,KETERSEDIAAN) values (9781455539741001,'978-1-4555-3974-1','Hamilton: The Revolution','Lin-Manuel Miranda','2016','Grand Central Publishing',1);
--------------------------------------------------------
--  DDL for Index BUKU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."BUKU_PK" ON "SIA"."PTI_BUKU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTI_BUKU
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_BUKU" ADD CONSTRAINT "BUKU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIA"."PTI_BUKU" MODIFY ("KETERSEDIAAN" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_BUKU" MODIFY ("PENERBIT" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_BUKU" MODIFY ("TH_TERBIT" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_BUKU" MODIFY ("PENGARANG" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_BUKU" MODIFY ("JUDUL" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_BUKU" MODIFY ("ISBN" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_BUKU" MODIFY ("ID" NOT NULL ENABLE);
