--------------------------------------------------------
--  File created - Friday-March-31-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTI_PINJAM
--------------------------------------------------------

  CREATE TABLE "SIA"."PTI_PINJAM" 
   (	"ID_PEMINJAM" VARCHAR2(20 BYTE), 
	"ID_BUKU" VARCHAR2(14 BYTE), 
	"TANGGAL_PINJAM" DATE, 
	"WAKTU_PINJAM" NUMBER, 
	"TANGGAL_KEMBALI" DATE, 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SIA.PTI_PINJAM
SET DEFINE OFF;
Insert into SIA.PTI_PINJAM (ID_PEMINJAM,ID_BUKU,TANGGAL_PINJAM,WAKTU_PINJAM,TANGGAL_KEMBALI,STATUS) values ('145314000','9781449356569',to_date('31-MAR-17','DD-MON-RR'),7,null,'N');
--------------------------------------------------------
--  Constraints for Table PTI_PINJAM
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_PINJAM" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PINJAM" MODIFY ("WAKTU_PINJAM" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PINJAM" MODIFY ("TANGGAL_PINJAM" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PINJAM" MODIFY ("ID_BUKU" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PINJAM" MODIFY ("ID_PEMINJAM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PTI_PINJAM
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_PINJAM" ADD CONSTRAINT "PTI_PINJAM_FK1" FOREIGN KEY ("ID_PEMINJAM")
	  REFERENCES "SIA"."PTI_ANGGOTA" ("ID") ENABLE;
  ALTER TABLE "SIA"."PTI_PINJAM" ADD CONSTRAINT "PTI_PINJAM_FK2" FOREIGN KEY ("ID_BUKU")
	  REFERENCES "SIA"."PTI_BUKU" ("ISBN") ENABLE;
--------------------------------------------------------
--  DDL for Trigger UBAHKETERSEDIAAN
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SIA"."UBAHKETERSEDIAAN" 
BEFORE INSERT OR UPDATE OF ID_BUKU, TANGGAL_PINJAM, TANGGAL_KEMBALI ON PTI_PINJAM
BEGIN
  IF UPDATING('TANGGAL_KEMBALI') THEN UPDATE PTI_BUKU SET
  KETERSEDIAAN = KETERSEDIAAN+1 WHERE (ID = ID_BUKU.PTI_PINJAM);
  IF INSERTING('PTI_PINJAM') THEN UPDATE PTI_BUKU SET
  KETERSEDIAAN = KETERSEDIAAN-1 WHERE (ID = ID_BUKU.PTI_PINJAM);
  END IF;
  END IF;
  END;
/
ALTER TRIGGER "SIA"."UBAHKETERSEDIAAN" DISABLE;
