CREATE OR REPLACE TRIGGER UbahKetersediaan
BEFORE INSERT OR UPDATE OF ID_BUKU, TANGGAL_PINJAM, TANGGAL_KEMBALI ON PTI_PINJAM
BEGIN
  IF UPDATING('TANGGAL_KEMBALI') THEN UPDATE PTI_BUKU SET
  KETERSEDIAAN = KETERSEDIAAN+1 WHERE (ID = ID_BUKU.PTI_PINJAM);
  IF INSERTING('PTI_PINJAM') THEN UPDATE PTI_BUKU SET
  KETERSEDIAAN = KETERSEDIAAN-1 WHERE (ID = ID_BUKU.PTI_PINJAM);
  END IF;
  END IF;
  END;